import { subDays, subHours } from 'date-fns';

const now = new Date();

export const customersData = [
  {
    id: '5e887ac47eed253091be10cb',
    address: {
      city: 'Manila',
      country: 'Philippines',
      state: 'Metro Manila',
      street: '1234 Taft Avenue',
    },
    createdAt: subDays(subHours(now, 7), 1).getTime(),
    email: 'juan.delacruz@gmail.com',
    name: 'Juan dela Cruz',
    phone: '0912-345-6789',
  },
  {
    id: '5e887b209c28ac3dd97f6db5',
    address: {
      city: 'Quezon City',
      country: 'Philippines',
      state: 'Metro Manila',
      street: '5678 Katipunan Avenue',
    },
    createdAt: subDays(subHours(now, 1), 2).getTime(),
    email: 'maria.santos@gmail.com',
    name: 'Maria Santos',
    phone: '0917-890-1234',
  },
  {
    id: '5e887b7602bdbc4dbb234b27',
    address: {
      city: 'Cebu City',
      country: 'Philippines',
      state: 'Cebu',
      street: '4321 Mango Street',
    },
    createdAt: subDays(subHours(now, 4), 2).getTime(),
    email: 'luis.cruz@gmail.com',
    name: 'Luis Cruz',
    phone: '0922-987-6543',
  },
  {
    id: '5e86809283e28b96d2d38537',
    address: {
      city: 'Makati City',
      country: 'Philippines',
      state: 'Metro Manila',
      street: '8769 Ayala Avenue',
    },
    createdAt: subDays(subHours(now, 11), 2).getTime(),
    email: 'maria.gonzales@gmail.com',
    name: 'Maria Gonzales',
    phone: '0918-765-4321',
  },
  {
    id: '5e86805e2bafd54f66cc95c3',
    address: {
      city: 'Davao City',
      country: 'Philippines',
      state: 'Davao',
      street: '2468 Durian Street',
    },
    createdAt: subDays(subHours(now, 7), 3).getTime(),
    email: 'jose.reyes@gmail.com',
    name: 'Jose Reyes',
    phone: '0920-123-4567',
  },
  {
    id: '5e887a1fbefd7938eea9c981',
    address: {
      city: 'Iloilo City',
      country: 'Philippines',
      state: 'Iloilo',
      street: '1357 Mango Lane',
    },
    createdAt: subDays(subHours(now, 5), 4).getTime(),
    email: 'luz.santos@gmail.com',
    name: 'Luz Santos',
    phone: '0915-678-9012',
  },
  {
    id: '5e887d0b3d090c1b8f162003',
    address: {
      city: 'Baguio City',
      country: 'Philippines',
      state: 'Benguet',
      street: '9876 Pine Street',
    },
    createdAt: subDays(subHours(now, 15), 4).getTime(),
    email: 'ramon.garcia@gmail.com',
    name: 'Ramon Garcia',
    phone: '0921-234-5678',
  },
  {
    id: '5e88792be2d4cfb4bf0971d9',
    address: {
      city: 'Cagayan de Oro',
      country: 'Philippines',
      state: 'Misamis Oriental',
      street: '5432 Riverfront Road',
    },
    createdAt: subDays(subHours(now, 2), 5).getTime(),
    email: 'maria.rodriguez@gmail.com',
    name: 'Maria Rodriguez',
    phone: '0916-345-6789',
  },
  {
    id: '5e8877da9a65442b11551975',
    address: {
      city: 'Bacolod City',
      country: 'Philippines',
      state: 'Negros Occidental',
      street: '7890 Sugarcane Lane',
    },
    createdAt: subDays(subHours(now, 8), 6).getTime(),
    email: 'josefina.santos@gmail.com',
    name: 'Josefina Santos',
    phone: '0925-678-9012',
  },
  {
    id: '5e8680e60cba5019c5ca6fda',
    address: {
      city: 'Cebu City',
      country: 'Philippines',
      state: 'Cebu',
      street: '1011 Mango Street',
    },
    createdAt: subDays(subHours(now, 1), 9).getTime(),
    email: 'pedro.cruz@gmail.com',
    name: 'Pedro Cruz',
    phone: '0913-456-7890',
  },
  {
    id: '101',
    address: {
      city: 'Mandaluyong City',
      country: 'Philippines',
      state: 'Metro Manila',
      street: '2468 Shaw Boulevard',
    },
    createdAt: new Date().getTime(),
    email: 'andres.santos@gmail.com',
    name: 'Andres Santos',
    phone: '0912-456-7890',
  },
  {
    id: '102',
    address: {
      city: 'Makati City',
      country: 'Philippines',
      state: 'Metro Manila',
      street: '6789 Paseo de Roxas',
    },
    createdAt: new Date().getTime(),
    email: 'lucia.gonzales@gmail.com',
    name: 'Lucia Gonzales',
    phone: '0917-890-5678',
  },
  {
    id: '103',
    address: {
      city: 'Davao City',
      country: 'Philippines',
      state: 'Davao',
      street: '1111 Durian Avenue',
    },
    createdAt: new Date().getTime(),
    email: 'manuel.tan@gmail.com',
    name: 'Manuel Tan',
    phone: '0922-123-4567',
  },
  {
    id: '104',
    address: {
      city: 'Cebu City',
      country: 'Philippines',
      state: 'Cebu',
      street: '2222 Mango Street',
    },
    createdAt: new Date().getTime(),
    email: 'carmen.delacruz@gmail.com',
    name: 'Carmen dela Cruz',
    phone: '0918-765-9876',
  },
  {
    id: '105',
    address: {
      city: 'Quezon City',
      country: 'Philippines',
      state: 'Metro Manila',
      street: '3333 Katipunan Road',
    },
    createdAt: new Date().getTime(),
    email: 'carlos.garcia@gmail.com',
    name: 'Carlos Garcia',
    phone: '0920-234-5678',
  },
  {
    id: '106',
    address: {
      city: 'Cagayan de Oro',
      country: 'Philippines',
      state: 'Misamis Oriental',
      street: '4444 Coastal Drive',
    },
    createdAt: new Date().getTime(),
    email: 'cristina.rodriguez@gmail.com',
    name: 'Cristina Rodriguez',
    phone: '0915-678-2345',
  },
  {
    id: '107',
    address: {
      city: 'Mandaluyong City',
      country: 'Philippines',
      state: 'Metro Manila',
      street: '5555 Shaw Boulevard',
    },
    createdAt: new Date().getTime(),
    email: 'eduardo.santos@gmail.com',
    name: 'Eduardo Santos',
    phone: '0921-345-6789',
  },
  {
    id: '108',
    address: {
      city: 'Makati City',
      country: 'Philippines',
      state: 'Metro Manila',
      street: '6666 Ayala Avenue',
    },
    createdAt: new Date().getTime(),
    email: 'filomena.gonzales@gmail.com',
    name: 'Filomena Gonzales',
    phone: '0916-456-7890',
  },
  {
    id: '109',
    address: {
      city: 'Davao City',
      country: 'Philippines',
      state: 'Davao',
      street: '7777 Durian Street',
    },
    createdAt: new Date().getTime(),
    email: 'gabriel.tan@gmail.com',
    name: 'Gabriel Tan',
    phone: '0925-567-8901',
  },
  {
    id: '110',
    address: {
      city: 'Cebu City',
      country: 'Philippines',
      state: 'Cebu',
      street: '8888 Mango Lane',
    },
    createdAt: new Date().getTime(),
    email: 'hannah.delacruz@gmail.com',
    name: 'Hannah dela Cruz',
    phone: '0913-567-8901',
  },
  {
    id: '111',
    address: {
      city: 'Quezon City',
      country: 'Philippines',
      state: 'Metro Manila',
      street: '9999 Katipunan Avenue',
    },
    createdAt: new Date().getTime(),
    email: 'ignacio.garcia@gmail.com',
    name: 'Ignacio Garcia',
    phone: '0912-456-7890',
  },
  {
    id: '112',
    address: {
      city: 'Cagayan de Oro',
      country: 'Philippines',
      state: 'Misamis Oriental',
      street: '1010 Coastal Road',
    },
    createdAt: new Date().getTime(),
    email: 'isabel.rodriguez@gmail.com',
    name: 'Isabel Rodriguez',
    phone: '0917-890-1234',
  },
  {
    id: '113',
    address: {
      city: 'Mandaluyong City',
      country: 'Philippines',
      state: 'Metro Manila',
      street: '2020 Shaw Boulevard',
    },
    createdAt: new Date().getTime(),
    email: 'javier.santos@gmail.com',
    name: 'Javier Santos',
    phone: '0922-987-6543',
  },
  {
    id: '114',
    address: {
      city: 'Makati City',
      country: 'Philippines',
      state: 'Metro Manila',
      street: '3030 Ayala Avenue',
    },
    createdAt: new Date().getTime(),
    email: 'karla.gonzales@gmail.com',
    name: 'Karla Gonzales',
    phone: '0918-765-4321',
  },
  {
    id: '115',
    address: {
      city: 'Davao City',
      country: 'Philippines',
      state: 'Davao',
      street: '4040 Durian Street',
    },
    createdAt: new Date().getTime(),
    email: 'lucas.tan@gmail.com',
    name: 'Lucas Tan',
    phone: '0920-123-4567',
  },
  {
    id: '116',
    address: {
      city: 'Cebu City',
      country: 'Philippines',
      state: 'Cebu',
      street: '5050 Mango Street',
    },
    createdAt: new Date().getTime(),
    email: 'maricela.delacruz@gmail.com',
    name: 'Maricela dela Cruz',
    phone: '0915-678-9012',
  },
  {
    id: '117',
    address: {
      city: 'Quezon City',
      country: 'Philippines',
      state: 'Metro Manila',
      street: '6060 Katipunan Avenue',
    },
    createdAt: new Date().getTime(),
    email: 'nathan.garcia@gmail.com',
    name: 'Nathan Garcia',
    phone: '0921-234-5678',
  },
  {
    id: '118',
    address: {
      city: 'Cagayan de Oro',
      country: 'Philippines',
      state: 'Misamis Oriental',
      street: '7070 Coastal Drive',
    },
    createdAt: new Date().getTime(),
    email: 'olivia.rodriguez@gmail.com',
    name: 'Olivia Rodriguez',
    phone: '0916-345-6789',
  },
  {
    id: '119',
    address: {
      city: 'Mandaluyong City',
      country: 'Philippines',
      state: 'Metro Manila',
      street: '8080 Shaw Boulevard',
    },
    createdAt: new Date().getTime(),
    email: 'pablo.santos@gmail.com',
    name: 'Pablo Santos',
    phone: '0925-678-9012',
  },
  {
    id: '120',
    address: {
      city: 'Makati City',
      country: 'Philippines',
      state: 'Metro Manila',
      street: '9090 Ayala Avenue',
    },
    createdAt: new Date().getTime(),
    email: 'quincy.gonzales@gmail.com',
    name: 'Quincy Gonzales',
    phone: '0913-456-7890',
  },
];
