import { subDays, subHours } from 'date-fns';

const now = new Date();

export const deliveriesData = [
  {
    id: '5e887ac47eed253091be10cb',
    order_id: 'ORD-COD-0001',
    customer: 'Senyor Agila',
    product: 'Sofa Footings High Quality Plastic Upholstery',
    seller: 'Juan Dela Cruz',
    price: '651',
    status: 'delivered',
    createdAt: subDays(subHours(now, 7), 1).getTime(),
  },
  {
    id: '5e887b209c28ac3dd97f6db5',
    order_id: 'ORD-COD-0002',
    customer: 'Zildjian Panaman',
    product: 'Leather Upholstery Custom Model NMAX Seat',
    seller: 'Maria Santos',
    price: '707',
    status: 'delivered',
    createdAt: subDays(subHours(now, 4), 2).getTime(),
  },
  {
    id: '5e887b7602bdbc4dbb234b27',
    order_id: 'ORD-COD-0003',
    customer: 'Mami Oni',
    product: 'Charol Synthetic Leather for Car Seat',
    seller: 'Luis Cruz',
    price: '95',
    status: 'shipped',
    createdAt: subDays(subHours(now, 11), 2).getTime(),
  },
  {
    id: '5e86809283e28b96d2d38537',
    order_id: 'ORD-COD-0004',
    customer: 'Manny Pacquiao',
    product: 'Mitsushi Staple Gun Tacker Heavy Duty',
    seller: 'Maria Gonzales',
    price: '165',
    status: 'shipped',
    createdAt: subDays(subHours(now, 7), 3).getTime(),
  },
  {
    id: '5e86805e2bafd54f66cc95c3',
    order_id: 'ORD-COD-0005',
    customer: 'Rendon Labador',
    product: 'Nylon Thread Ticket for Upholstery',
    seller: 'Jose Reyes',
    price: '129',
    status: 'processing',
    createdAt: subDays(subHours(now, 5), 4).getTime(),
  },
  {
    id: '5e887a1fbefd7938eea9c981',
    order_id: 'ORD-COD-0006',
    customer: 'Francine Diaz',
    product: 'Anti-Slip Checkered Plate Rubber Flooring Matting',
    seller: 'Rogie Aldueza',
    price: '158',
    status: 'shipped',
    createdAt: subDays(subHours(now, 15), 4).getTime(),
  },
  {
    id: '120',
    order_id: 'ORD-COD-0007',
    customer: 'Jonas Candelario',
    product: 'Uratex Foam Customizable for Upholstery',
    seller: 'Jonas Candelario',
    price: '261',
    status: 'delivered',
    createdAt: subDays(subHours(now, 19), 4).getTime(),
  },
];
